models/Order.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "orders".
 *
 * @property int $id
 * @property string $customer_name
 * @property string $email
 * @property string $phone
 * @property string $feedback
 * @property int $orders_userId
 *
 * @property Comment[] $comments
 */
class Order extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'orders';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['email', 'phone', 'feedback'], 'string'],
            [['orders_userId'], 'integer'],
            [['customer_name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customer_name' => 'Customer Name',
            'email' => 'Email',
            'phone' => 'Phone',
            'feedback' => 'Feedback',
            'orders_userId' => 'Orders User ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComments()
    {
        return $this->hasMany(Comment::className(), ['postId' => 'id']);
    }

    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'orders_userId']);
    }
}

controllers/OrdersController.php
<?php
/**
 * Created by PhpStorm.
 * User: maksim
 * Date: 24.10.18
 * Time: 12:59
 */

namespace app\controllers;

use yii\web\Controller;
use app\models\Order;


class OrdersController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index',[
            'title' => 'Order list',
            'orders' => Order::find()->all(),
        ]);
    }

    public function actionView($id)
    {
        $order = Order::findOne($id);

        return $this->render('view', [
            'order'=> $order,
            ]
        );
    }

    public function actionAdd()
    {
        if(\Yii::$app->request->isPost) {
           // $data = \Yii::$app->request->post();

            $order = new Order();
            $order->load(['Order' => \Yii::$app->request->post()]);
            $order->save();

            $this->redirect('/orders/view?id=' . $order->id);
        }

        return $this->render('add');
    }
}

views/orders/add.php
<div class="col-md-8 col-lg-offset-2">
    <h1 class="text-center">
        Add Order
    </h1>
    <form action="/orders/add" method="post" class="order-create">
        <input type="hidden" name="<?= Yii::$app->request->csrfParam; ?>" value="<?= Yii::$app->request->csrfToken; ?>" />
        <div class="form-group">
            <label for="customer_name">Customer name</label>
            <input type="text" class="form-control" id="customer_name" name="customer_name">
        </div>
        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" name="email">
        </div>
        <div class="form-group">
            <label for="phone">Phone</label>
            <input type="tel" class="form-control" id="phone" name="phone" >
        </div>
        <div class="form-group">
            <label for="feedback">Example textarea</label>
            <textarea class="form-control" id="feedback" name="feedback"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

views/orders/index.php
<?php
/** @var \app\models\Order[] $orders */
?>

<div class="orders">
    <h1>
        <?=$title?>
    </h1>
    <div class="list">
        <?php foreach ($orders as $order) :?>
            <div>
                <p class="border">
                    <?=$order->user['username']. '<br>';?>
                    <?=$order->customer_name . '<br>';?>
                    <?=$order->email . '<br>';?>
                    <?=$order->phone . '<br>';?>
                </p>
                <a class="btn btn-primary" href="/orders/view?id=<?=$order->id?>">Show more...</a>
            </div>
        <?php endforeach ;?>
    </div>
</div>

views/orders/view.php
<?php
/** @var \app\models\Order[] $orders */
$comment = new \app\models\Comment();
$comment->postId = $order->id;
use yii\widgets\ActiveForm;
?>
<div class = "text-center">
    <h1>
        <?=$order->customer_name . '<br>';?>
    </h1>
    <p>
        <?=$order->feedback;?><?=$order->id;?>
    </p>
    <a class="btn btn-primary" href="/orders/index">Back</a>
</div>


<?php
$form = ActiveForm::begin([
    'action' => '/comments/create'
])
?>

<?=$form
    ->field($comment, 'postId')
    ->hiddenInput()
    ->label(false)
?>

<?=$form->field($comment, 'body')->textarea() ?>

    <div class="form-group">
        <button type="submit" class="btn btn-success">Save</button>
    </div>

<?php ActiveForm::end() ?>

<?php foreach($order->comments as $comment) : ?>
    <p><?=$comment->body ?><span><?=date('Y.m.d. H:i:s', $comment->createdAt)?></span></p>

<?php endforeach ?>